### ISSUE TITLE
Retrieve All Diagrams

### ISSUE THREAD

**Issue by fishcharlie** [fdesjardins/airport-diagrams#1]
Is it possible using this package to retrieve all available airport diagrams?

**Comment by fdesjardins** [comment]
Hey @fishcharlie, you'll need a list of the airport identifiers first, as this package utilizes the search functionality provided on this page: https://www.faa.gov/air_traffic/flight_info/aeronav/digital_products/dtpp/search/

There's another package I know of that could help get the identifiers: https://github.com/FAA-Aviation-Data-Portal/nfdc-airport-data#readme.

One way you could do it is to grab the airport codes for each US state, something like this:
```js
const airportData = require("@faa-aviation-data-portal/nfdc-airport-data");
const airportDiagrams = require("airport-diagrams");

(async () => {
  const { states } = await airportData.states();

  let allAirports = [];
  for (const state of states.slice(0, 1)) {
    const airports = await airportData.facilities({ state });
    allAirports = allAirports.concat(airports);
  }
  allAirports = allAirports.filter(airport => airport.IcaoIdentifier !== null);

  let allDiagrams = [];
  for (const airport of allAirports) {
    const diagrams = await airportDiagrams(airport.IcaoIdentifier);
    if (diagrams) {
      console.log(diagrams);
      allDiagrams = allDiagrams.concat(diagrams);
    }
  }
})();
```

That'd give you all diagrams for all airports with an ICAO identifier. Note, this will take quite a while to run, and I did `states.slice(0,1)` so this example only fetches diagrams for Alaska (AK). But, it should give you a decent place to start.

Not sure what your use case is, but aeronav also publishes archives on this page https://www.faa.gov/air_traffic/flight_info/aeronav/digital_products/dtpp/ which might work for you.

**Comment by fdesjardins** [comment]
Closing this, but feel free to provide feedback @fishcharlie, or let me know if you need any more info. Thanks!
